excluded:
  - Lumi.xcodeproj

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  - first_where
  - force_unwrapping
  - redundant_type_annotation
  - sorted_imports
  - unneeded_parentheses_in_closure_argument

disabled_rules:
  - todo

line_length:
  warning: 120
  error: 160

identifier_name:
  min_length: 2
  excluded:
    - id

type_name:
  min_length: 3
